package jclec.binarray;

import jclec.IDistance;
import jclec.IIndividual;
import jclec.JCLEC;

/**
 * Hamming Distance.
 *
 * @author Sebastian Ventura
 */

public class HammingDistance implements IDistance, JCLEC {
    //////////////////////////////////////////////////////////////////////
    // -------------------------------------------- Serialization constant
    //////////////////////////////////////////////////////////////////////

    /**
     * Generated by Eclipse
     */

    private static final long serialVersionUID = -5292752152678382460L;

    //////////////////////////////////////////////////////////////////////
    // ---------------------------------------------------- Public methods
    //////////////////////////////////////////////////////////////////////

    // IDistance interface

    @Override
    public double distance(IIndividual one, IIndividual other) {
        // Individual genotypes
        byte[] gone = ((BinArrayIndividual) other).getGenotype();
        byte[] gother = ((BinArrayIndividual) other).getGenotype();
        // Setting Hamming distance
        int distance = 0;
        int gl = gone.length;
        for (int i = 0; i < gl; i++) {
            if (gone[i] != gother[i])
                distance++;
        }
        // Returns hamming distance
        return distance;
    }
}
